### ISSUE TITLE
Path/file error creating study reportx

### ISSUE THREAD

**Issue by jackdolgin** [scienceverse/reg#16]
Already enjoying this package! I'm able to follow [these steps](https://scienceverse.github.io/scienceverse/articles/registration.html) through ['Save the study archive file'](https://scienceverse.github.io/scienceverse/articles/registration.html#save-the-study-archive-file), but then I run into the following issue when I try to create a pre-registration report. (I'm doing this in a .R file but still had the same issue with a .Rmd too); not sure if I'm doing something wrong though!

```r
study_report(mystudy, template="postreg", filename = "postreg")
# Saving to/Users/.../analysis/postreg.html
# Error in abs_path(input) : The file '' does not exist.
# In addition: Warning message:
# In normalizePath(path, winslash = winslash, mustWork = mustWork) :
 #  path[1]="": No such file or directory
```
Again, everything else up to that point, like creating the JSON, works which makes me wonder why there would still be a path issue. Thanks in advance (and for the package)!

**Comment by debruine** [comment]
The adding .html to the filename. I think it uses the extension to determine how to render the file. I’ll look at it tomorrow and add a default if the file name doesn’t contain a valid extension.

**Comment by jackdolgin** [comment]
oh i forgot to mention that I also had tried that too without any luck. Sounds good!
```r
study_report(mystudy, template="postreg", filename = "postreg.html")
```

**Comment by debruine** [comment]
Did you set your working directory manually as "/Users/.../analysis/" or is the ... just truncation? I always get the full path there. What do you get when you run `getwd()` just before `study_report()`?

**Comment by jackdolgin** [comment]
The ... is just truncation for posting on GitHub purposes (I didn't set the working directory manually), and when I run `getwd()` just before `study_report()` I still get the full path

**Comment by debruine** [comment]
Closing because major code revision makes this one impossible to replicate now.
