### ISSUE TITLE
create a shiny app 

### ISSUE THREAD

**Issue by jcolomb** [scienceverse/reg#20]
the functions are quite difficult to work with for non-R coders, It might be interesting to create a small shiny app to get inputs added via web forms instead of command lines.
OUPS: did not see it, there is already one... Maybe you want to present it in the readme file ?

Another path would be to get all the information in a yaml/json format, as it would be already easier to write than having to code it. the application would then more be a verification tool for the yaml file. 

maybe a combination of these different approaches would make it more accessible ??

**Comment by debruine** [comment]
The function scivrs_app() opens up such a shiny app :) 

It’s not finished yet, so is quite buggy, but does a lot of what you’d want and creates a live-updated JSON structure as you fill things out. 

I’m swamped with start-of-term teaching, but am giving talks on scienceverse to CoS and Montreal in November, so am aim to get a lot of updates done before then. 

Let me know if you’re keen to collaborate.

**Comment by debruine** [comment]
The app is coming along well and should be ready for use soon.

**Comment by debruine** [comment]
The app is coming along well and should be ready for use soon.
